model:
  name: 'PCB_p6'
  num_stripes: 6
  share_conv: False
  return_features: False

data:
  type: 'image'
  sources: ['market1501']
  targets: ['market1501']
  height: 384
  width: 128
  combineall: False
  transforms: ['random_flip']
  save_dir: 'log/pcb_p6'


test:
  batch_size: 512
  dist_metric: 'euclidean'
  # dist_metric: cosine
  normalize_feature: True
  evaluate: True
  eval_freq: -1
  rerank: False
  visactmap: False