model:
  name: 'PCB_p6'
  pretrained: False
  # resume: '/home/hy/vscode/reid-custom/log/tensorboard/log/resnet50/model/model.pth.tar-60'
  num_stripes: 6
  share_conv: False
  return_features: False

data:
  type: 'image'
  sources: ['market1501']
  targets: ['market1501']
  height: 384
  width: 128
  combineall: False
  transforms: ['random_flip']
  save_dir: 'log/pcb_p6_save'

test:
  batch_size: 512
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  eval_freq: -1
  rerank: False
  visactmap: False