model:
  name: 'PCB_p6'
  pretrained: False
  # resume: '/home/hy/vscode/reid-custom/log/tensorboard/log/resnet50/model/model.pth.tar-60'
  num_stripes: 6
  share_conv: False
  return_features: False

data:
  type: 'image'
  sources: ['market1501']
  targets: ['market1501']
  height: 384
  width: 128
  combineall: True
  transforms: ['random_flip']
  save_dir: 'log/pcb_p6_save'

loss:
  name: 'softmax'
  softmax:
    label_smooth: True

train:
  optim: 'sgd'
  lr: 0.1
  max_epoch: 5
  batch_size: 4
  fixbase_epoch: 0
  open_layers: ['classifier']
  lr_scheduler: 'cosine'

test:
  batch_size: 4
  dist_metric: 'cosine'
  normalize_feature: False
  evaluate: False
  eval_freq: -1
  rerank: False
  visactmap: False