model:
  name: 'PCB_p6'
  pretrained: False
  # resume: '/home/hy/vscode/reid-custom/log/tensorboard/log/resnet50/model/model.pth.tar-60'
  num_stripes: 6
  share_conv: False
  return_features: False

data:
  type: 'image'
  sources: ['market1501']
  targets: ['market1501']
  height: 384
  width: 128
  combineall: False
  transforms: ['random_flip']
  save_dir: 'log/pcb_p6_save'

loss:
  name: 'softmax'
  softmax:
    label_smooth: True

train:
  optim: 'sgd'
  lr: 0.1
  new_layers: ['local_conv_list','fc_list']
  staged_lr: True
  base_lr_mult: 0.1
  max_epoch: 60
  batch_size: 64
  fixbase_epoch: 0
  lr_scheduler: 'single_step'
  stepsize: [20]
  gamma: 0.1
  open_layers: []

sgd:
  nesterov: True
  momentum: 0.9

test:
  batch_size: 512
  dist_metric: 'cosine'
  normalize_feature: False
  evaluate: False
  eval_freq: -1
  rerank: False
  visactmap: False